from pathlib import Path

TARGET = Path('/tmp/chainacobblemon/src/main/java/com/andrewbristowx/chainacobblemon/events/treasure/TreasureHuntService.java')
s = TARGET.read_text()

old = '''        for (int z = 0; z < plan.height; z++) for (int x = 0; x < plan.width; x++) {\n            Cell c = new Cell(x, z);\n            BlockPos center = cellCenter(minX, minZ, c);\n            carveRoom(world, center);\n            if (((x + z) & 1) == 0) {\n                world.setBlockState(center.up(4), Blocks.LIGHT.getDefaultState().with(Properties.LEVEL_15, 15), Block.NOTIFY_LISTENERS);\n            }\n            for (Cell n : plan.neighbors(c)) if (compareCell(c, n) < 0) carveCorridor(world, center, cellCenter(minX, minZ, n));\n        }\n'''
new = '''        for (int z = 0; z < plan.height; z++) for (int x = 0; x < plan.width; x++) {\n            Cell c = new Cell(x, z);\n            BlockPos center = cellCenter(minX, minZ, c);\n            carveRoom(world, center);\n            for (Cell n : plan.neighbors(c)) if (compareCell(c, n) < 0) carveCorridor(world, center, cellCenter(minX, minZ, n));\n        }\n\n        // Alpha.23: illuminate after every room/corridor has been carved. Previously the corridor\n        // carving pass could erase LIGHT blocks placed earlier, leaving long sections almost black.\n        for (int z = 0; z < plan.height; z++) for (int x = 0; x < plan.width; x++) {\n            Cell c = new Cell(x, z);\n            BlockPos center = cellCenter(minX, minZ, c);\n            placeInvisibleLight(world, center.up(4));\n            for (Cell n : plan.neighbors(c)) if (compareCell(c, n) < 0) {\n                BlockPos other = cellCenter(minX, minZ, n);\n                BlockPos midpoint = new BlockPos((center.getX() + other.getX()) / 2, BASE_Y + 5,\n                        (center.getZ() + other.getZ()) / 2);\n                placeInvisibleLight(world, midpoint);\n            }\n        }\n'''
assert old in s, 'maze lighting block not found'
s = s.replace(old, new, 1)

old = '''        // Safe start pad. Intermediate platforms become narrower as the tier rises, while every\n        // center-to-center jump remains within vanilla sprint-jump limits.\n        BlockPos startBlock = run.parkourStartPos.down();\n        fillPlatform(world, startBlock, 1, theme.accent.getDefaultState());\n        for (int i = 1; i < platforms.size(); i++) {\n            int radius = eventRun.stars <= 1 ? 1 : (eventRun.stars == 2 && i % 3 == 0 ? 1 : 0);\n            fillPlatform(world, platforms.get(i), radius, i % 3 == 0 ? theme.accent.getDefaultState() : theme.floor.getDefaultState());\n        }\n'''
new = '''        // Safe start pad. Difficulty now comes from route length, turns and platform size rather\n        // than impossible height. Every upward transition is at most one block.\n        BlockPos startBlock = run.parkourStartPos.down();\n        fillPlatform(world, startBlock, 1, theme.accent.getDefaultState());\n        for (int i = 1; i < platforms.size(); i++) {\n            int radius;\n            if (eventRun.stars == 1) {\n                // Tier 1 is no longer a chain of giant 3x3 pads: alternate small landing pads with\n                // occasional forgiving rest platforms.\n                radius = (i % 3 == 0) ? 1 : 0;\n            } else if (eventRun.stars == 2) {\n                radius = (i % 5 == 0) ? 1 : 0;\n            } else {\n                radius = 0;\n            }\n            fillPlatform(world, platforms.get(i), radius, i % 4 == 0 ? theme.accent.getDefaultState() : theme.floor.getDefaultState());\n        }\n\n        // Strong, invisible route lighting. One source above every landing keeps the parkour readable\n        // without visible lamps or destroying the dungeon atmosphere.\n        for (BlockPos platform : platforms) placeInvisibleLight(world, platform.up(4));\n'''
assert old in s, 'parkour platform block not found'
s = s.replace(old, new, 1)

start = s.index('    private static List<BlockPos> parkourPlatforms(')
end = s.index('    private static void fillPlatform', start)
replacement = '''    private static List<BlockPos> parkourPlatforms(BlockPos startBlock, int stars) {\n        int jumps = switch (stars) {\n            case 1 -> 9;\n            case 2 -> 11;\n            case 3 -> 14;\n            case 4 -> 17;\n            default -> 20;\n        };\n        List<BlockPos> out = new ArrayList<>();\n        out.add(startBlock);\n        BlockPos current = startBlock;\n\n        // Deterministic wave shared by every participant. Horizontal/turn difficulty grows with tier,\n        // but vertical delta between consecutive platforms is strictly -1/0/+1. For an upward jump\n        // the X advance is capped at 2, so no tier can generate a 2+ block climb or a long rising leap.\n        int[] sideWave = {0, 1, 0, -1, -2, -1, 0, 1, 2, 1, 0, -1};\n        int relativeY = 0;\n        for (int i = 1; i <= jumps; i++) {\n            int desiredZ = startBlock.getZ() + sideWave[(i + stars) % sideWave.length];\n            int dz = desiredZ - current.getZ();\n            if (dz > 1) desiredZ = current.getZ() + 1;\n            if (dz < -1) desiredZ = current.getZ() - 1;\n\n            int dy = 0;\n            if (stars >= 2 && i % 5 == 2 && relativeY < 2) dy = 1;\n            else if (stars >= 3 && i % 5 == 4 && relativeY > 0) dy = -1;\n            else if (stars >= 4 && i % 7 == 0 && relativeY < 2) dy = 1;\n            if (relativeY + dy < 0) dy = 0;\n            if (relativeY + dy > 2) dy = 0;\n\n            int dx;\n            if (dy > 0) {\n                dx = 2; // safe one-block ascent\n            } else if (stars == 1) {\n                dx = (i % 4 == 0) ? 3 : 2;\n            } else if (stars <= 3) {\n                dx = (i % 3 == 0) ? 3 : 2;\n            } else {\n                // Higher tiers are longer and use more 3-block/diagonal landings, never vertical abuse.\n                dx = (i % 2 == 0) ? 3 : 2;\n            }\n\n            relativeY += dy;\n            current = new BlockPos(current.getX() + dx, current.getY() + dy, desiredZ);\n            out.add(current);\n        }\n        return List.copyOf(out);\n    }\n\n    private static void placeInvisibleLight(ServerWorld world, BlockPos pos) {\n        world.setBlockState(pos, Blocks.LIGHT.getDefaultState().with(Properties.LEVEL_15, 15), Block.NOTIFY_LISTENERS);\n    }\n\n'''
s = s[:start] + replacement + s[end:]

TARGET.write_text(s)
