plugins {
    id 'java'
    id 'application'
}

group = 'com.andrewbristowx.chainabridge'
version = '0.4.0-alpha.4'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.google.code.gson:gson:2.13.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = 'com.andrewbristowx.chainabridge.ChainaBridgeMain'
}

tasks.named('jar') {
    archiveBaseName = 'ChainaBridge'
    archiveVersion = '0.4.0-alpha.4'
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
    from {
        configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
